name: Challenges
version: ${version}
main: me.sirsam.challenges.Main
description: Challenges Plugin
author: SirSam
website: programming4life.github.io
api-version: "1.20"
loadbefore: [Essentials]

commands:
  challenge:
    description: Opens the challenges GUI.
    permission: op
    permission-message: You do not have permission to use this Command!
    usage: /<command>
    aliases: challenges
  timer:
    description: Allows you to control the challenges timer.
    permission: op
    permission-message: You do not have permission to use this Command!
    usage: /<command> [start|stop|pause|resume|reset|show|hide|set]